# Generated by Django 2.1.5 on 2019-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
            ],
        ),
    ]
