# Generated by Django 2.1.5 on 2019-03-01 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190301_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrity',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
