# Generated by Django 2.1.5 on 2019-03-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190301_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrity',
            options={'verbose_name': 'Celebrity', 'verbose_name_plural': 'Celebrities'},
        ),
    ]
